# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: queue.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\rdispatcher.v1\"\xcb\x01\n\x14\x41\x63\x63\x65ptMessageRequest\x12\x17\n\x0fidempotency_key\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12G\n\nattributes\x18\x04 \x03(\x0b\x32\x33.dispatcher.v1.AcceptMessageRequest.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\">\n\x15\x41\x63\x63\x65ptMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tduplicate\x18\x02 \x01(\x08\"M\n\x0fRegisterRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x16\n\x0e\x64ownstream_url\x18\x02 \x01(\t\x12\x13\n\x0b\x63onsumer_id\x18\x03 \x01(\t\"\'\n\x10RegisterResponse\x12\x13\n\x0b\x63onsumer_id\x18\x01 \x01(\t\"(\n\x11UnregisterRequest\x12\x13\n\x0b\x63onsumer_id\x18\x01 \x01(\t\"\x14\n\x12UnregisterResponse2\x8a\x02\n\x0cMessageQueue\x12Z\n\rAcceptMessage\x12#.dispatcher.v1.AcceptMessageRequest\x1a$.dispatcher.v1.AcceptMessageResponse\x12K\n\x08Register\x12\x1e.dispatcher.v1.RegisterRequest\x1a\x1f.dispatcher.v1.RegisterResponse\x12Q\n\nUnregister\x12 .dispatcher.v1.UnregisterRequest\x1a!.dispatcher.v1.UnregisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCEPTMESSAGEREQUEST_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_ACCEPTMESSAGEREQUEST_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_ACCEPTMESSAGEREQUEST']._serialized_start=31
  _globals['_ACCEPTMESSAGEREQUEST']._serialized_end=234
  _globals['_ACCEPTMESSAGEREQUEST_ATTRIBUTESENTRY']._serialized_start=185
  _globals['_ACCEPTMESSAGEREQUEST_ATTRIBUTESENTRY']._serialized_end=234
  _globals['_ACCEPTMESSAGERESPONSE']._serialized_start=236
  _globals['_ACCEPTMESSAGERESPONSE']._serialized_end=298
  _globals['_REGISTERREQUEST']._serialized_start=300
  _globals['_REGISTERREQUEST']._serialized_end=377
  _globals['_REGISTERRESPONSE']._serialized_start=379
  _globals['_REGISTERRESPONSE']._serialized_end=418
  _globals['_UNREGISTERREQUEST']._serialized_start=420
  _globals['_UNREGISTERREQUEST']._serialized_end=460
  _globals['_UNREGISTERRESPONSE']._serialized_start=462
  _globals['_UNREGISTERRESPONSE']._serialized_end=482
  _globals['_MESSAGEQUEUE']._serialized_start=485
  _globals['_MESSAGEQUEUE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
