# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import queue_pb2 as queue__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageQueueStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcceptMessages = channel.stream_stream(
                '/dispatcher.v1.MessageQueue/AcceptMessages',
                request_serializer=queue__pb2.AcceptMessageRequest.SerializeToString,
                response_deserializer=queue__pb2.AcceptMessageResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/dispatcher.v1.MessageQueue/Register',
                request_serializer=queue__pb2.RegisterRequest.SerializeToString,
                response_deserializer=queue__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/dispatcher.v1.MessageQueue/Unregister',
                request_serializer=queue__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=queue__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/dispatcher.v1.MessageQueue/Subscribe',
                request_serializer=queue__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=queue__pb2.SatwayMessage.FromString,
                _registered_method=True)
        self.AckMessage = channel.unary_unary(
                '/dispatcher.v1.MessageQueue/AckMessage',
                request_serializer=queue__pb2.AckMessageRequest.SerializeToString,
                response_deserializer=queue__pb2.AckMessageResponse.FromString,
                _registered_method=True)
        self.ConfigureTopics = channel.unary_unary(
                '/dispatcher.v1.MessageQueue/ConfigureTopics',
                request_serializer=queue__pb2.ConfigureTopicsRequest.SerializeToString,
                response_deserializer=queue__pb2.ConfigureTopicsResponse.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/dispatcher.v1.MessageQueue/ListTopics',
                request_serializer=queue__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=queue__pb2.ListTopicsResponse.FromString,
                _registered_method=True)


class MessageQueueServicer:
    """Missing associated documentation comment in .proto file."""

    def AcceptMessages(self, request_iterator, context):
        """Client streams publishes; server streams one response per request after SQLite commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Optional metadata about a consumer. Delivery is on Subscribe, not this call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister drops stored consumer metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Open a consume stream. Multiple subscribers on one topic compete:
        each message is sent to exactly one of them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMessage(self, request, context):
        """Confirm or reject a message received from Subscribe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureTopics(self, request, context):
        """Create or replace delivery and persistence for many topics at once.
        delivery is "single" (competing consumers, default) or "broadcast" (every live stream).
        persistence is "persistent" (store and deliver later, default) or "ephemeral"
        (deliver only to live Subscribe streams; drop if nobody is connected).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """List stored topic delivery and persistence configs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageQueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcceptMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.AcceptMessages,
                    request_deserializer=queue__pb2.AcceptMessageRequest.FromString,
                    response_serializer=queue__pb2.AcceptMessageResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=queue__pb2.RegisterRequest.FromString,
                    response_serializer=queue__pb2.RegisterResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=queue__pb2.UnregisterRequest.FromString,
                    response_serializer=queue__pb2.UnregisterResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=queue__pb2.SubscribeRequest.FromString,
                    response_serializer=queue__pb2.SatwayMessage.SerializeToString,
            ),
            'AckMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMessage,
                    request_deserializer=queue__pb2.AckMessageRequest.FromString,
                    response_serializer=queue__pb2.AckMessageResponse.SerializeToString,
            ),
            'ConfigureTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureTopics,
                    request_deserializer=queue__pb2.ConfigureTopicsRequest.FromString,
                    response_serializer=queue__pb2.ConfigureTopicsResponse.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=queue__pb2.ListTopicsRequest.FromString,
                    response_serializer=queue__pb2.ListTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispatcher.v1.MessageQueue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispatcher.v1.MessageQueue', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageQueue:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcceptMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dispatcher.v1.MessageQueue/AcceptMessages',
            queue__pb2.AcceptMessageRequest.SerializeToString,
            queue__pb2.AcceptMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.v1.MessageQueue/Register',
            queue__pb2.RegisterRequest.SerializeToString,
            queue__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.v1.MessageQueue/Unregister',
            queue__pb2.UnregisterRequest.SerializeToString,
            queue__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dispatcher.v1.MessageQueue/Subscribe',
            queue__pb2.SubscribeRequest.SerializeToString,
            queue__pb2.SatwayMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.v1.MessageQueue/AckMessage',
            queue__pb2.AckMessageRequest.SerializeToString,
            queue__pb2.AckMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.v1.MessageQueue/ConfigureTopics',
            queue__pb2.ConfigureTopicsRequest.SerializeToString,
            queue__pb2.ConfigureTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.v1.MessageQueue/ListTopics',
            queue__pb2.ListTopicsRequest.SerializeToString,
            queue__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
