[project]
name = "cangling-broker"
version = "0.1.46"
description = "Python producer and consumer for cangling-broker"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "zhangjianshe", email = "zhangjianshe@gmail.com" }]
license = { text = "Apache-2.0" }
dependencies = [
    "grpcio>=1.83.0",
    "protobuf>=5.28.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
urls.Homepage = "https://github.com/zhangjianshe/cangling-broker"
urls.Repository = "https://github.com/zhangjianshe/cangling-broker"

[project.optional-dependencies]
dev = ["grpcio-tools>=1.83.0", "build", "twine"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["cangling_broker", "cangling_broker.*"]
